server{
    listen 8082;
    listen [::]:8082;
    server_name -;

    root /var/www/index.html;
    index index.html
    access_log /var/log/nginx/nguyenthiyen-k24cntt2-access.log;
    error_log /var/log/nginx/nguyenthiyen-k24cntt2-error.log;
    location / {
       try-files $uri $uri/ =404;

    }
}